### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by regenerativep** [OpenCliqueCraft/splinter-proxy#39]
Process stdin so that we could do some basic commands like `stop`, `list`, `kick`, `say`.
Could also use the same command system for client commands, and from that we'd also want permissions or access levels.

**Comment by RKDUDE02** [comment]
Do you mean executing commands on all splinter servers?
I imagine it would look something like this.
/splinter global-execute (insert command here).

**Comment by regenerativep** [comment]
> Do you mean executing commands on all splinter servers?

@RKDUDE02 I am thinking that we probably want implement a command system for splinter. splinter-proxy at the moment does not accept any input while the server is running other than the code that exists to handle player connections.
First, splinter-proxy would be made to read from stdin, so that someone could just type something into the server console like with a normal Minecraft server or like in BungeeCord. splinter-proxy does not do anything with stdin at the moment.
Next, some command system would be necessary, such that when stdin is processed, it can identify the command you're trying to run, the arguments you've put in, and run code specific to that command.
Some basic commands to make things in the proxy would be like

- `stop` to shut down the proxy, similar to `end` in BungeeCord or `stop` in a normal Minecraft server. Maybe we want to shut down the Minecraft simulation servers at the same time, but it would still make sense to have the proxy do special things with it so it is not just command forwarding.
- `list` like in a normal server to list the players connected. Such a command would likely work better on the side of the proxy since the proxy already knows exactly who is connected and asking each Minecraft simulation server for that would be much more hassle.
- `kick` can also be done proxy side. The proxy can just disconnect players and bypass going through the simulation servers for that. All the sim servers would see is the player disconnecting.
- `say` broadcasts a chat message to every client. Proxy already handles chat; no chat from the players (except commands at the moment) go to the simulation servers, so it makes sense to keep it within the proxy.

Command forwarding can also be useful. A shorter version like `fwd [server id | "all"] [command and aguments]` might be better ex. `fwd 0 summon minecraft:wither 0 128 0` or `fwd all kill @e`. Command forwarding however would either require controlling the simulation server's i/o pipes, accessing a server's RCON, or probably the easiest since a simulation server side plugin will be necessary, doing it through a plugin on the side of the simulation server.

**Comment by wg4568** [comment]
@regenerativep Commands can be forwarded by just sending a chat message packet starting with a `/`, no trickery needed. The simulation servers handle it correctly.

**Comment by regenerativep** [comment]
> @regenerativep Commands can be forwarded by just sending a chat message packet starting with a `/`, no trickery needed. The simulation servers handle it correctly.

@wg4568 Yes, we already have a form of packet forwarding. I was intending to explain a more general form of forwarding where you can specify a specific server to send a command to and sending a command to a server from the proxy console without any op players online.
