### ISSUE TITLE
Implement packet compression

### ISSUE THREAD

**Issue by regenerativep** [OpenCliqueCraft/splinter-proxy#9]
Currently both the client-proxy and proxy-server connections are uncompressed. The client is connecting to the proxy on an uncompressed connection, which may be undesirable in the future, and the servers require an extra explicit setting to turn off compression on their end.
[craftio-rs](https://github.com/Twister915/craftio-rs) is supposed to have compression features. Would likely have to add parts of the protocol to both client-proxy side and proxy-server side.

**Comment by wg4568** [comment]
Closed by https://github.com/OpenCliqueCraft/splinter-proxy/pull/19
